#!/usr/bin/env bash
AOC_TEMPFILE=/tmp/aoc_env
local_path=$(realpath $(dirname ${BASH_SOURCE[0]}))
source "${local_path}/lib/_common.sh"

dependencies=("docker" "curl" "yq")
missing_deps=()
for dep in "${dependencies[@]}"; do
  if ! which "$dep" &> /dev/null; then
    missing_deps+=("$dep")
  fi
done

cmd=$1
shift
if [[ -f "${local_path}/lib/${cmd}.sh" ]]; then
  source "${local_path}/lib/${cmd}.sh"
  main "$@"
else
  echo "Unknown command: $cmd"
  usage
  exit 1
fi
