languages:
  bash:
    container: bash:latest
    run: bash solution.sh
  c:
    container: gcc:latest
    run: /bin/sh run.sh
  clojure:
    container: clojure:latest
    run: clojure -M -i solution.clj -m solution
  crystal:
    container: crystallang/crystal:latest
    run: crystal run solution.cr --
  d:
    container: dlanguage/dmd
    run: /bin/sh run.sh
  dart:
    container: dart:latest
    run: dart solution.dart
  elixir:
    container: elixir:latest
    run: elixir solution.exs
  erlang:
    container: erlang:latest
    run: /bin/sh run.sh
  fsharp:
    container: mcr.microsoft.com/dotnet/sdk:latest
    run: dotnet fsi solution.fsx
  go:
    container: golang:latest
    run: go run solution.go
  groovy:
    container: groovy:latest
    run: groovy solution.groovy
  haskell:
    container: haskell:latest
    run: /bin/sh run.sh
  haxe:
    container: haxe:latest
    run: haxe --run Solution
  io:
    run: io solution.io
  java:
    container: openjdk:17
    run: /bin/sh run.sh
  julia:
    container: julia:latest
    run: julia solution.jl
  kotlin:
    run: /bin/sh run.sh
  lua:
    container: alpinelinux/lua-turbo
    run: lua solution.lua
  miniscript:
    run: miniscript solution.ms
  nim:
    container: nimlang/nim
    run: /bin/sh run.sh
  node:
    container: node:latest
    run: node solution.js
  ocaml:
    container: ocaml/opam:latest
    run: ocaml solution.ml
  perl:
    container: perl:latest
    run: perl solution.pl
  php:
    container: php:cli
    run: php solution.php
  prolog:
    container: swipl:latest
    run: swipl solution.pl
  python:
    container: python:latest
    run: python solution.py
  qbasic:
    run: /bin/sh run.sh
  r:
    container: r-base:latest
    run: Rscript solution.R
  racket:
    container: racket/racket
    run: racket solution.rkt
  ruby:
    container: ruby:latest
    run: ruby solution.rb
  rust:
    container: rust:latest
    run: cargo run --quiet --bin solution
  scala:
    container: sbtscala/scala-sbt:graalvm-ce-22.3.3-b1-java17_1.9.7_3.3.1
    run: /bin/sh run.sh
  spl:
    container: python:latest
    run: /bin/sh run.sh
  sql:
    container: postgres:latest
    run: /bin/sh run.sh
  swift:
    container: swift:latest
    run: swift solution.swift
  tcl:
    container: esolang/tcl
    run: tclsh solution.tcl
  uiua:
    run: uiua solution.ua
  v:
    run: v run solution.v
  wren:
    run: wren_cli solution.wren
  yasl:
    run: yasl solution.yasl
  zig:
    run: /bin/sh run.sh
