languages:
  bash:
    container: bash:latest
    run: bash solution.sh
  ruby:
    container: ruby:latest
    run: ruby solution.rb
  rust:
    container: rust:latest
    run: cargo run --quiet --bin solution
  python:
    container: python:latest
    run: python solution.py
  node:
    container: node:latest
    run: node solution.js
  go:
    container: golang:latest
    run: go run solution.go
  haskell:
    container: haskell:latest
    run: runhaskell solution.hs
  elixir:
    container: elixir:latest
    run: elixir solution.exs
  erlang:
    container: erlang:latest
    run: escript solution.erl
  swift:
    container: swift:latest
    run: swift solution.swift
  julia:
    container: julia:latest
    run: julia solution.jl
  lua:
    container: alpinelinux/lua-turbo
    run: lua solution.lua
  ocaml:
    container: ocaml/opam:latest
    run: ocaml solution.ml
  clojure:
    container: clojure:latest
    run: clojure -M -i solution.clj -m solution
