languages:
  bash:
    container: bash:latest
    run: bash solution.sh
  ruby:
    container: ruby:latest
    run: ruby solution.rb
  rust:
    container: rust:latest
    run: cargo run --quiet --bin solution
