DIM AS INTEGER FILENUM, CHAR
DIM AS STRING INPUTFILE, PART, CHAR_STR
DIM AS INTEGER SUM
DIM AS INTEGER HASH
DIM LABEL_ARRAY(0 to 256, 0 to 256) AS STRING
DIM FOCAL_ARRAY(0 to 256, 0 to 256) AS INTEGER
DIM AS INTEGER BOX, IDX
DIM AS STRING LABEL

SUM = 0
HASH = 0

INPUTFILE = COMMAND$(1)
PART = COMMAND$(2)

FILENUM = FREEFILE
OPEN INPUTFILE FOR INPUT AS #FILENUM

IF PART = "2" GOTO PART2
READING: CHAR_STR = INPUT(1, #FILENUM)
CHAR = CHAR_STR[0]
IF CHAR = 44 OR CHAR <= 10 GOTO TERMINALCHAR
HASH = HASH + CHAR
HASH = HASH * 17
HASH = HASH MOD 256
GOTO READING
TERMINALCHAR: SUM = SUM + HASH
IF CHAR <= 10 GOTO DONE
HASH = 0
GOTO READING

PART2:
LABEL = ""
READLABEL: 
CHAR_STR = INPUT(1, #FILENUM)
CHAR = CHAR_STR[0]
IF CHAR_STR = "=" GOTO ADDLENS
IF CHAR_STR = "-" GOTO REMLENS
LABEL = LABEL + CHAR_STR
HASH = HASH + CHAR
HASH = HASH * 17
HASH = HASH MOD 256
GOTO READLABEL

ADDLENS: 
CHAR_STR = INPUT(1, #FILENUM) ' Focal length
CHAR = CHAR_STR[0]
IDX = 0
ADDSCAN:
IF LABEL_ARRAY(HASH, IDX) = "" OR LABEL_ARRAY(HASH, IDX) = LABEL GOTO DOADD
IDX = IDX + 1
GOTO ADDSCAN
DOADD: 
LABEL_ARRAY(HASH, IDX) = LABEL
FOCAL_ARRAY(HASH, IDX) = CHAR - 48 ' "9" -> 9
GOTO FINISHOP

REMLENS: 
IDX = 0
REMSCAN:
IF LABEL_ARRAY(HASH, IDX) = "" GOTO FINISHOP
IF LABEL_ARRAY(HASH, IDX) = LABEL GOTO SHIFTSCAN
IDX = IDX + 1
GOTO REMSCAN
SHIFTSCAN: IDX = IDX + 1
LABEL_ARRAY(HASH, IDX - 1) = LABEL_ARRAY(HASH, IDX)
FOCAL_ARRAY(HASH, IDX - 1) = FOCAL_ARRAY(HASH, IDX)
IF LABEL_ARRAY(HASH, IDX) = "" GOTO FINISHOP
GOTO SHIFTSCAN

FINISHOP: 
CHAR_STR = INPUT(1, #FILENUM)
CHAR = CHAR_STR[0]
IF CHAR <= 10 GOTO SUMS
HASH = 0
LABEL = ""
GOTO READLABEL

SUMS: 
HASH = 0
SUMBOX: IDX = 0
IF LABEL_ARRAY(HASH, IDX) = "" GOTO NEXTBOX
SUMLENS: SUM = SUM + (1 + HASH) * (IDX + 1) * FOCAL_ARRAY(HASH, IDX)
IDX = IDX + 1
IF LABEL_ARRAY(HASH, IDX) <> "" GOTO SUMLENS
NEXTBOX: IF HASH > 255 GOTO DONE
HASH = HASH + 1
GOTO SUMBOX

DONE: CLOSE #FILENUM
PRINT "" & SUM ' AVOIDS EXTRA SPACING FOR SOME REASON
